steps:
  - label: ":python: Tests"
    timeout_in_minutes: 10
    commands:
#      - "pyenv global 2.7.16 3.4.10 3.5.7 3.6.9"
#      - "python setup.py install"
#      - "pip install tox"
      - "tox"
    plugins:
      - docker#v3.3.0:
          image: "n42org/docker-tox:3.4.0"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
